In [1]:
import tensorflow as tf

# Initialization of Tensors

In [2]:
x = tf.constant(4, shape=(2, 3), dtype=tf.float32)
print(x)

x = tf.constant([[1,2,3], [4,5,6]])
print(x)

x = tf.ones((3,3))
x = tf.zeros((2,3))
x = tf.eye(3) # I for indentity matrix
print(x)

x = tf.random.normal((3,3), mean=0, stddev=1)
print(x)

x = tf.random.uniform((1,3), minval=0, maxval=1)
print(x)

x = tf.range(9)
x = tf.range(start=2, limit=10, delta=2)
print(x)

x = tf.cast(x, dtype=tf.float32)
print(x)

# tf.float(16,32,64)
# tf.int(8,16,32,64)
# tf.bool

tf.Tensor(
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]], shape=(5, 3), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[-0.5824109   0.00575445 -0.70409054]
 [ 1.2370088   0.14000773 -0.25178263]
 [-1.3984641   1.0626781   1.9436882 ]], shape=(3, 3), dtype=float32)
tf.Tensor([[0.30042756 0.47865582 0.43452346]], shape=(1, 3), dtype=float32)
tf.Tensor([2 4 6 8], shape=(4,), dtype=int32)
tf.Tensor([2. 4. 6. 8.], shape=(4,), dtype=float32)


# Mathematical Operations

In [7]:
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

# Equivalent ways
z1 = tf.add(x, y)
z = x + y 
print(z)

z = x - y # tf.subtract
print(z)

z = x*y   # tf.multiply
print(z)

z = x/y   # tf.divide
print(z)

z = x**3
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)
tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)
tf.Tensor([ 1  8 27], shape=(3,), dtype=int32)


In [10]:
z = tf.tensordot(x, y, axes=1)
print(z)

z = tf.reduce_sum(x*y, axis=0)
print(z)

x = tf.random.normal((2,3))
y = tf.random.normal((3,4))
z = tf.matmul(x, y)
print(z)
z = x @ y
print(z)

tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor(
[[ 1.3255230e+00  8.5738558e-01  1.9884634e+00 -2.0508623e+00]
 [ 3.4774125e-01  1.0220036e-03  6.4738262e-01 -8.4035349e-01]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[ 1.3255230e+00  8.5738558e-01  1.9884634e+00 -2.0508623e+00]
 [ 3.4774125e-01  1.0220036e-03  6.4738262e-01 -8.4035349e-01]], shape=(2, 4), dtype=float32)


# Indexing

In [17]:
x = tf.constant([0, 1, 2, 3, 4, 5, 6, 7])

print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])
print(x[5:1:-2]) # start:end:step in [start, end)

indices = tf.constant([0, 3])
x_ind   = tf.gather(x, indices)
print(x_ind)

tf.Tensor([0 1 2 3 4 5 6 7], shape=(8,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([0 2 4 6], shape=(4,), dtype=int32)
tf.Tensor([7 6 5 4 3 2 1 0], shape=(8,), dtype=int32)
tf.Tensor([5 3], shape=(2,), dtype=int32)
tf.Tensor([0 3], shape=(2,), dtype=int32)


In [18]:
x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

print(x[0:2, :])

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


# Reshaping

In [19]:
x = tf.range(9)
print(x)

x = tf.reshape(x, (3,3))
print(x)

x = tf.transpose(x, perm=[1, 0])
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)


In [24]:
x = tf.reshape(tf.range(27), (3,3,3))
print(x)

print('\n==============================\n')

x = tf.transpose(x, perm=[1, 0, 2])
print(x)

print('\n===============================\n')

x = tf.transpose(x, perm=[2, 1, 0])
print(x)

tf.Tensor(
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]], shape=(3, 3, 3), dtype=int32)


tf.Tensor(
[[[ 0  1  2]
  [ 9 10 11]
  [18 19 20]]

 [[ 3  4  5]
  [12 13 14]
  [21 22 23]]

 [[ 6  7  8]
  [15 16 17]
  [24 25 26]]], shape=(3, 3, 3), dtype=int32)


tf.Tensor(
[[[ 0  3  6]
  [ 9 12 15]
  [18 21 24]]

 [[ 1  4  7]
  [10 13 16]
  [19 22 25]]

 [[ 2  5  8]
  [11 14 17]
  [20 23 26]]], shape=(3, 3, 3), dtype=int32)
